/**
 * The Word answers: common five-letter English words, committed to the repo.
 *
 * Never fetched over the network — the plugin has no `http` capability at all
 * (see the README's zero-token and no-network notes). A test asserts that every
 * entry is exactly five letters, so a typo here fails the suite.
 */

export const WORDS: readonly string[] = [
  "about", "above", "abuse", "actor", "acute", "admit", "adopt", "adult", "after", "again",
  "agent", "agree", "ahead", "alarm", "album", "alert", "alike", "alive", "allow", "alone",
  "along", "alter", "among", "anger", "angle", "angry", "apart", "apple", "apply", "arena",
  "argue", "arise", "armed", "array", "arrow", "aside", "asset", "avoid", "awake", "award",
  "aware", "badly", "baker", "bases", "basic", "basis", "beach", "began", "begin", "begun",
  "being", "below", "bench", "birth", "black", "blame", "blank", "blast", "blind", "block",
  "blood", "board", "boost", "booth", "bound", "brain", "brand", "brass", "brave", "bread",
  "break", "breed", "brief", "bring", "broad", "broke", "brown", "brush", "build", "built",
  "bunch", "burst", "buyer", "cabin", "cable", "candy", "canal", "cargo", "carry", "carve",
  "catch", "cause", "cease", "chain", "chair", "chalk", "chaos", "charm", "chart", "chase",
  "cheap", "check", "chest", "chief", "child", "chose", "chunk", "civil", "claim", "class",
  "clean", "clear", "clerk", "click", "cliff", "climb", "clock", "close", "cloth", "cloud",
  "coach", "coast", "could", "count", "court", "cover", "crack", "craft", "crash", "crazy",
  "cream", "crime", "cross", "crowd", "crown", "crude", "curve", "cycle", "daily", "dance",
  "dated", "dealt", "death", "debut", "decay", "delay", "dense", "depth", "diary", "dirty",
  "doing", "doubt", "dozen", "draft", "drama", "drank", "drawn", "dream", "dress", "dried",
  "drink", "drive", "drove", "dying", "eager", "early", "earth", "eight", "elect", "elite",
  "empty", "ended", "enemy", "enjoy", "enter", "entry", "equal", "error", "essay", "event",
  "every", "exact", "exist", "extra", "faced", "facts", "faith", "false", "fancy", "fatal",
  "fault", "favor", "feast", "fence", "fever", "fewer", "fiber", "field", "fifth", "fifty",
  "fight", "final", "first", "fixed", "flame", "flash", "fleet", "flesh", "float", "flood",
  "floor", "flour", "fluid", "focus", "force", "forth", "forty", "forum", "found", "frame",
  "fraud", "fresh", "front", "frost", "fruit", "fully", "funny", "giant", "given", "giver",
  "glass", "globe", "glory", "glove", "goods", "grace", "grade", "grain", "grand", "grant",
  "grape", "graph", "grass", "grave", "great", "green", "greet", "grief", "grill", "gross",
  "group", "grown", "guard", "guess", "guest", "guide", "guilt", "happy", "harsh", "haste",
  "hatch", "heard", "heart", "heavy", "hedge", "hello", "hence", "hobby", "holds", "honey",
  "honor", "horse", "hotel", "house", "human", "humor", "hurry", "ideal", "image", "imply",
  "index", "inner", "input", "irony", "issue", "ivory", "jeans", "jelly", "jewel", "joint",
  "jolly", "judge", "juice", "keeps", "kneel", "knife", "knock", "known", "label", "labor",
  "large", "laser", "later", "laugh", "layer", "learn", "lease", "least", "leave", "legal",
  "lemon", "level", "lever", "light", "limit", "linen", "links", "liver", "lives", "local",
  "lodge", "logic", "loose", "lorry", "loser", "loved", "lower", "loyal", "lucky", "lunar",
  "lunch", "lying", "magic", "major", "maker", "march", "match", "maybe", "mayor", "meant",
  "medal", "media", "melon", "mercy", "merge", "merit", "metal", "meter", "midst", "might",
  "minor", "minus", "mixed", "model", "moist", "money", "month", "moral", "motor", "mount",
  "mouse", "mouth", "movie", "music", "naked", "named", "nasty", "naval", "nerve", "never",
  "newly", "night", "noble", "noise", "north", "noted", "novel", "nurse", "ocean", "offer",
  "often", "onion", "opera", "orbit", "order", "organ", "other", "ought", "ounce", "outer",
  "owner", "paint", "panel", "panic", "paper", "party", "pasta", "patch", "pause", "peace",
  "peach", "pearl", "pedal", "penny", "phase", "phone", "photo", "piano", "piece", "pilot",
  "pitch", "pixel", "place", "plain", "plane", "plant", "plate", "plaza", "point", "polar",
  "porch", "pound", "power", "press", "price", "pride", "prime", "print", "prior", "prize",
  "probe", "proof", "proud", "prove", "pulse", "punch", "pupil", "purse", "queen", "query",
  "quest", "queue", "quick", "quiet", "quilt", "quite", "quota", "quote", "radar", "radio",
  "raise", "rally", "ranch", "range", "rapid", "ratio", "reach", "react", "ready", "realm",
  "rebel", "refer", "reign", "relax", "relay", "renew", "repay", "reply", "rider", "ridge",
  "rifle", "right", "rigid", "rival", "river", "roast", "robin", "robot", "rocky", "rough",
  "round", "route", "royal", "rugby", "ruler", "rural", "sadly", "saint", "salad", "sales",
  "salon", "sauce", "scale", "scare", "scene", "scent", "scope", "score", "scout", "screw",
  "seats", "seize", "sense", "serve", "setup", "seven", "shade", "shaft", "shake", "shall",
  "shame", "shape", "share", "sharp", "sheep", "sheet", "shelf", "shell", "shift", "shine",
  "shirt", "shock", "shoot", "shore", "short", "shown", "sight", "silly", "since", "sixth",
  "sixty", "skill", "skirt", "sleep", "slice", "slide", "slope", "small", "smart", "smell",
  "smile", "smoke", "snake", "sober", "solar", "solid", "solve", "sorry", "sound", "south",
  "space", "spare", "speak", "speed", "spell", "spend", "spent", "spice", "spine", "spite",
  "split", "spoke", "sport", "spray", "squad", "stack", "staff", "stage", "stain", "stake",
  "stamp", "stand", "stare", "start", "state", "steam", "steel", "steep", "steer", "stern",
  "stick", "stiff", "still", "stock", "stone", "stood", "store", "storm", "story", "stove",
  "strap", "straw", "strip", "stuck", "study", "stuff", "style", "sugar", "suite", "sunny",
  "super", "sweat", "sweep", "sweet", "swift", "swing", "sword", "table", "taken", "tales",
  "talks", "taste", "taxes", "teach", "teams", "tears", "teeth", "tempo", "tenth", "thank",
  "theft", "their", "theme", "there", "these", "thick", "thing", "think", "third", "those",
  "three", "threw", "throw", "thumb", "tiger", "tight", "timer", "tired", "title", "toast",
  "today", "token", "tooth", "topic", "torch", "total", "touch", "tough", "tower", "towns",
  "trace", "track", "trade", "trail", "train", "trait", "trash", "treat", "trend", "trial",
  "tribe", "trick", "tried", "tries", "truck", "truly", "trunk", "trust", "truth", "tulip",
  "twice", "twist", "uncle", "under", "union", "unite", "unity", "until", "upper", "upset",
  "urban", "usage", "usual", "vague", "valid", "value", "valve", "vapor", "vault", "venue",
  "verse", "video", "villa", "vinyl", "viral", "virus", "visit", "vital", "vivid", "vocal",
  "voice", "voted", "vowel", "wagon", "waist", "waste", "watch", "water", "waved", "weary",
  "weave", "wedge", "weigh", "weird", "whale", "wheat", "wheel", "where", "which", "while",
  "white", "whole", "whose", "widen", "widow", "width", "windy", "witch", "woman", "women",
  "world", "worry", "worse", "worst", "worth", "would", "wound", "wrist", "write", "wrong",
  "wrote", "yacht", "yield", "young", "yours", "youth", "zebra",
];
